# Generated by Django 2.2.8 on 2021-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridient', models.CharField(db_index=True, max_length=150)),
                ('calories', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
