# Generated by Django 2.2.8 on 2021-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='ingridient',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
